name: Generate CV PDF

on:
  workflow_dispatch:
  push:
    paths:
      - 'cv.html'
      - 'scripts/render-cv.mjs'
      - '.github/workflows/generate-cv-pdf.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: |
          npm init -y --silent
          npm i puppeteer@22 --silent

      - name: Render cv.html to PDF
        run: node scripts/render-cv.mjs

      - name: Commit PDF if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            assets/pdf/Zhexiang(Bruce) Li - CV.pdf
            assets/pdf/cv.pdf
          message: 'chore: auto-generate CV PDFs from cv.html'
          default_author: github_actions
